apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: receipt-frontend-cert
  namespace: istio-system
spec:
  secretName: receipt-frontend-credential
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 34.171.160.35.nip.io
  dnsNames:
    - 34.171.160.35.nip.io

      