apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: receipt-frontend-cert
  namespace: prod
spec:
  secretName: receipt-frontend-credential
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "34.135.155.239.nip.io"  # Using the actual IP address
  # secretTemplate:
  #   annotations:
  #     cert-manager.io/alt-names: "true"


      