apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
  - ../../base
  - ingress.yaml
  - certificate.yaml

patches:
  - path: patch-service.yaml
  - path: patch-deployment.yaml
