apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
  - ../../base
  - istio-gateway.yaml
patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
