apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-frontend-green
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt-frontend
      env: green
  template:
    metadata:
      labels:
        app: receipt-frontend
        env: green
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"         # Or /actuator/prometheus if using Spring Boot
        prometheus.io/port: "80"
    spec:
      containers:
      - name: receipt-frontend
        image: venkatakurathitud/receipt-frontend:latest
        ports:
        - containerPort: 22137
        env:
        - name: WEBSERVICE_HOST
          value: "receipt-backend-service.default.svc.cluster.local"
        - name: WEBSERVICE_PORT
          value: "80"
        - name: EXPOSED_PORT
          value: "22137"
        - name: ENV_LABEL
          value: "green"
        livenessProbe:
          httpGet:
            path: /
            port: 22137
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 22137
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"