apiVersion: v1
kind: Service
metadata:
  name: receipt-frontend-service
  namespace: default
spec:
  selector:
    app: receipt-frontend
    env: blue  # Initially select the blue environment
  ports:
    - port: 80
      targetPort: 22137
  type: LoadBalancer
