apiVersion: v1
kind: Service
metadata:
  name: receipt-frontend-service
spec:
  selector:
    app: receipt-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 22137
    nodePort: 30001
  type: NodePort