apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-frontend-green
spec:
  progressDeadlineSeconds: 600  # 10 minutes max
  replicas: 0  # Will be scaled to 1 on first deploy
  selector:
    matchLabels:
      app: receipt-frontend
      env: green
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: receipt-frontend
        env: green
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "22137"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: receipt-frontend
        image: venkatakurathitud/receipt-frontend
        ports:
        - containerPort: 22137
        env:
        - name: WEBSERVICE_HOST
          value: "receipt-backend-service.prod.svc.cluster.local"
        - name: WEBSERVICE_PORT
          value: "80"
        - name: EXPOSED_PORT
          value: "22137"
        - name: ENV_LABEL
          value: "green"
        startupProbe:
          httpGet:
            path: /
            port: 22137
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30  # 30 attempts = 150s max  
        livenessProbe:
          httpGet:
            path: /
            port: 22137
          initialDelaySeconds: 15
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 22137
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"