apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-blue.yaml
  - deployment-green.yaml
  - service.yaml
  - hpa.yaml
  - network-policy.yaml
  - pdb.yaml
# images:
#   - name: venkatakurathitud/receipt-frontend
#     newTag: SHORT_SHA  # Will be replaced in workflow