apiVersion: v1
kind: Service
metadata:
  name: receipt-frontend-service
spec:
  selector:
    app: receipt-frontend
    env: blue  # Default, patched by overlays
  ports:
    - port: 80
      targetPort: 22137
  type: LoadBalancer