apiVersion: v1
kind: Service
metadata:
  name: receipt-frontend-service
spec:
  selector:
    app: receipt-frontend
    env: green  # Default to green for first deployment
  ports:
    - port: 80
      targetPort: 22137
  type: LoadBalancer