apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
  - path: monitoring-patch.yaml