apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-frontend-blue
spec:
  selector:
    matchLabels:
      app: receipt-frontend
      env: blue
  template:
    metadata:
      labels:
        app: receipt-frontend
        env: blue
    spec:
      containers:
      - name: receipt-frontend
        env:
        - name: WEBSERVICE_HOST
          value: receipt-backend-service.dev.svc.cluster.local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-frontend-green
spec:
  selector:
    matchLabels:
      app: receipt-frontend
      env: green
  template:
    metadata:
      labels:
        app: receipt-frontend
        env: green
    spec:
      containers:
      - name: receipt-frontend
        env:
        - name: WEBSERVICE_HOST
          value: receipt-backend-service.dev.svc.cluster.local
